name: Tap CI

on:
  push:
  pull_request:

jobs:
  formula-check:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Audit formula
        run: brew audit --formula upcloud-box
